name: Build C00

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 8
          distribution: adopt
          java-package: jre
          
      - name: Create out folder
        run: mkdir -p out/
          
      - name: Build C00.bin
        run: |
          sed -i s/debugMode=1/debugMode=0/ tickflow/config/debug.tickflow
          java -jar tickompiler.jar c tickflow/ bin/
          java -jar tickompiler.jar p bin/ shorts.bin out/C00.bin
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Latest C00
          path: out/C00.bin
          
  debug:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Java
        uses: actions/setup-java@v3.9.0
        with:
          java-version: 8
          distribution: adopt
          java-package: jre
          
      - name: Create out/debug folder
        run: mkdir -p out/debug
          
      - name: Build C00.bin
        run: |
          sed -i s/debugMode=0/debugMode=1/ tickflow/config/debug.tickflow
          java -jar tickompiler.jar c tickflow/ bin/
          java -jar tickompiler.jar p bin/ shorts.bin out/debug/C00.bin
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: Debug C00
          path: out/debug/C00.bin
